---
grails:
    profile: web-plugin
    codegen:
        defaultPackage: grails.plugins.mail.oauth
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    groovy:
        template:
            check-template-location: false
    jmx:
        unique-names: true

---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
---
hibernate:
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: 'org.hibernate.cache.ehcache.EhCacheRegionFactory'

management:
    endpoints:
        enabled-by-default: false

dataSource:
    pooled: true
    jmxExport: true
    driverClassName: org.h2.Driver
    username: sa
    password:

environments:
    development:
        dataSource:
            dbCreate: create-drop
            url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    test:
        dataSource:
            dbCreate: update
            url: jdbc:h2:mem:testDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    production:
        dataSource:
            dbCreate: update
            url: jdbc:h2:./prodDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
            properties:
                jmxEnabled: true
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
grails:
    mail:
        username: xyz
        oAuth:
            daemon: false
            enabled: false
            client_id: b5351907-3792-4590-ac3a-ee9ba737e7d1
            secret_val: DvW7Q~CaMbkKrX2DDifpHQbOOasr3k-RrmSAN
            api_scope: https://outlook.office.com/SMTP.Send offline_access
            callback_url: http://localhost:9090/mailOAuth/callback
            tenant_id: common
            token:
                refresh:
                    frequency: 300       # every 5 minutes
                    time:
                        difference: 600    # if less than 10 minutes then refresh
            redirect:
                uri: /mailOAuth/index
            graph:
                enabled: false
                attachmentMax: 3       # MB
                http:
                    connectTimeout: 30
                    writeTimeout: 600
                    readTimeout: 600
            health:
                check:
                    disabled: false
        reader:
            enabled: false
            graph:
                callbackUrl: http://localhost:8082/readerToken/callback
                redirect_uri: /emailConfig
            health:
                check:
                    disabled: false
